package(default_visibility = ["//visibility:public"])

cc_library(
    name = "zpages",
    hdrs = glob(["include/**/zpages/*.h"]),
    strip_include_prefix = "include",
)

cc_library(
    name = "http_server",
    hdrs = glob(["include/**/http/server/*.h"]),
    strip_include_prefix = "include",
)
